objects/Price_List__c/Price_List__c.object-meta.xml
<CustomObject>
    <label>PriceBook</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PriceBooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Price_List_Record__c/Price_List_Record__c.object-meta.xml
<CustomObject>
    <label>Price List Record</label>
    <nameField>
        <label>Price List Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price List Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Price_List_Record__c/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <label>Price Book</label>
    <referenceTo>Price_List__c</referenceTo>
    <relationshipLabel>Price List Records</relationshipLabel>
    <relationshipName>Price_List_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/DeletePriceListRecords.cls
global class DeletePriceListRecords implements
    Database.Batchable<sObject>, Database.Stateful
{
    global Integer recordsProcessed = 0;
    private String recordId;
    private String recordTypeName;

    public DeletePriceListRecords(String Id,String recordName) {
        recordId = Id;
        recordTypeName = recordName;
    }
    global Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(
            'SELECT Id FROM Price_List_Record__c WHERE  Price_List__c =\''+ recordId +'\''
        );
    }
    
    global void execute (Database.BatchableContext bc, List<Price_List_Record__c> scope){
        List<Price_List_Record__c> plList = new List<Price_List_Record__c>();
        for (Price_List_Record__c plrecord : scope){
            plList.add(plRecord);
            recordsProcessed = recordsProcessed + 1;
        }
        delete plList;
    }
    
    global void finish (Database.BatchableContext bc){
       // System.debug(recordsProcessed + ' records processed. Delete!');
       // System.debug(bc.getJobId() + ' Job Id. delete!');
        if (recordTypeName == 'Product Price List'){
            Database.executeBatch(new GenerateProductPriceList(recordId),1000);
        }
        /*else if (recordTypeName == 'Regional Price List'){
            //Database.executeBatch(new GenerateRegionalPriceList(recordId),1000);
        }
        else if (recordTypeName == 'Customer Price List'){
           // Database.executeBatch(new GenerateCustomerPriceList(recordId),1000);
        }*/
           
    }
}