objects/Price_List__c/Price_List__c.object-meta.xml
<CustomObject>
    <label>PriceBook</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PriceBooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Price_List_Record__c/Price_List_Record__c.object-meta.xml
<CustomObject>
    <label>Price List Record</label>
    <nameField>
        <label>Price List Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price List Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Price_List_Record__c/fields/Density__c.field-meta.xml
<CustomField>
    <fullName>Density__c</fullName>
    <label>Density</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Price_List_Record__c/fields/Family_Adj_Amt__c.field-meta.xml
<CustomField>
    <fullName>Family_Adj_Amt__c</fullName>
    <label>Family Adj Amt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Price_List_Record__c/fields/Manual_Override_Amt__c.field-meta.xml
<CustomField>
    <fullName>Manual_Override_Amt__c</fullName>
    <label>Manual Override Amt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Price_List_Record__c/fields/Past_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Past_Revenue__c</fullName>
    <label>Past Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Price_List_Record__c/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <label>Price Book</label>
    <referenceTo>Price_List__c</referenceTo>
    <relationshipLabel>Price List Records</relationshipLabel>
    <relationshipName>Price_List_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Price_List_Record__c/fields/Product2Id__c.field-meta.xml
<CustomField>
    <fullName>Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product2Id</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Price List Records</relationshipLabel>
    <relationshipName>Price_List_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Price_List_Record__c/fields/Product_Adj_Amt__c.field-meta.xml
<CustomField>
    <fullName>Product_Adj_Amt__c</fullName>
    <label>Product Adj Amt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Price_List_Record__c/fields/Product_Family_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Family_Name__c</fullName>
    <label>Product Family Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Price_List_Record__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/PricebookEntry/fields/Density__c.field-meta.xml
<CustomField>
    <fullName>Density__c</fullName>
    <label>Density</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HDPE</fullName>
            </value>
            <value>
                <fullName>LDPE</fullName>
            </value>
            <value>
                <fullName>LLDPE</fullName>
            </value>
            <value>
                <fullName>LMDPE</fullName>
            </value>
            <value>
                <fullName>MDPE</fullName>
            </value>
            <value>
                <fullName>sHDPE</fullName>
            </value>
            <value>
                <fullName>sLLDPE</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/PricebookEntry/fields/Family_Adj_Amt__c.field-meta.xml
<CustomField>
    <fullName>Family_Adj_Amt__c</fullName>
    <label>Family Adj Amt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/PricebookEntry/fields/Manual_Override_Amt__c.field-meta.xml
<CustomField>
    <fullName>Manual_Override_Amt__c</fullName>
    <label>Manual Override Amt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/PricebookEntry/fields/Past_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Past_Revenue__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Past Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/PricebookEntry/fields/Product_Adj_Amt__c.field-meta.xml
<CustomField>
    <fullName>Product_Adj_Amt__c</fullName>
    <label>Product Adj Amt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/PricebookEntry/fields/Product_Family_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Family_Name__c</fullName>
    <label>Product Family</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/PricebookEntry/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/PricebookEntry/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Invalidated</fullName>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Product_Revenue__c/Product_Revenue__c.object-meta.xml
<CustomObject>
    <label>Product Revenue</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Revenue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sbaa__Approval__c/sbaa__Approval__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sbaa__Approval__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/ProductPriceListGeneration.cls
public with sharing class ProductPriceListGeneration {
    //private Id pricebookId;
    //public static sbaa__Approval__c[] approvals {get; set;} 

    /*public PriceListGeneration(ApexPages.StandardController stdController) {
        pricebookId = stdController.getId();
    }*/
    
    @AuraEnabled
    public static List<Price_List_Record__c> getInitResult(String recordId)
    {
        List<Price_List_Record__c> pbEntryList = [SELECT Product2Id__c,Name,Product_Family_Name__c,Density__c,Base_Price__c,Family_Adj_Amt__c,Product_Adj_Amt__c,Manual_Override_Amt__c,UnitPrice__c,Past_Revenue__c,Quantity__c,Start_Date__c,End_date__c,Status__c FROM Price_List_Record__c WHERE  Price_List__c = :recordId];
        return pbEntryList;
    }
   
    @AuraEnabled
    public static void generatePriceListRecords(String recordId){
       
        String recordTypeName = [SELECT RecordType.Name FROM Price_List__c WHERE Id = :recordId].RecordType.Name;
        Id batchId = Database.executeBatch(new DeletePriceListRecords(recordId,recordTypeName),1000);
    }
   /* 
    private static PricebookEntry setProductRevenue(PricebookEntry pbEntry,String productName){
        List <Product_Revenue__c> prList = [SELECT Past_Revenue__c,Quantity__c FROM Product_Revenue__c WHERE Name = :productName];
        if (prList.size()>0){
            for(Product_Revenue__c prRecord : prList){
                pbEntry.Past_Revenue__c = prRecord.Past_Revenue__c;
                pbEntry.Quantity__c = prRecord.Quantity__c;
            }
            
        }
        return pbEntry;
    }*/

   
/*
    

    @AuraEnabled
    public static void onSubmit(String recordId) {
        if (recordId != null) {
            sbaa.ApprovalAPI.submit(recordId, sbaa__Approval__c.Price_Book__c);
        }
    }
    
    public void onPreview() {
        if (pricebookId != null) {
            approvals = sbaa.ApprovalAPI.preview(pricebookId, sbaa__Approval__c.Price_Book__c);
        }
    }*/
}