objects/Base_Price_Policy__c/Base_Price_Policy__c.object-meta.xml
<CustomObject>
    <label>Base Price Policy</label>
    <nameField>
        <displayFormat>BPP-{0000000}</displayFormat>
        <label>Base Price Policy ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Base Price Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Base_Price_Policy__c/fields/Base_Price__c.field-meta.xml
<CustomField>
    <fullName>Base_Price__c</fullName>
    <label>Base Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Base_Price_Policy__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

objects/Base_Price_Policy__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

objects/Base_Price_Policy__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Base_Price_Policy__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

objects/Base_Price_Policy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

objects/Family_Price_Adjustment__c/Family_Price_Adjustment__c.object-meta.xml
<CustomObject>
    <label>Family Price Adjustment</label>
    <nameField>
        <displayFormat>FPA-{0000000}</displayFormat>
        <label>Family Price Adjustment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Family Price Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Family_Price_Adjustment__c/fields/Family_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Family_Adjustment__c</fullName>
    <label>Family Adjustment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Pricebook2/fields/End_date__c.field-meta.xml
<CustomField>
    <fullName>End_date__c</fullName>
    <label>End date</label>
    <type>Date</type>
</CustomField>

objects/Pricebook2/fields/Manual_Override__c.field-meta.xml
<CustomField>
    <fullName>Manual_Override__c</fullName>
    <label>Manual Override</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

objects/Pricebook2/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Polyethylene</fullName>
            </value>
            <value>
                <fullName>Olefines</fullName>
            </value>
            <value>
                <fullName>Expandable Styrenics</fullName>
            </value>
            <value>
                <fullName>Valves</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Pricebook2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Invalidated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Pricebook2/fields/Target_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Target_Revenue__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Target Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/PricebookEntry/fields/Density__c.field-meta.xml
<CustomField>
    <fullName>Density__c</fullName>
    <label>Density</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HDPE</fullName>
            </value>
            <value>
                <fullName>LDPE</fullName>
            </value>
            <value>
                <fullName>LLDPE</fullName>
            </value>
            <value>
                <fullName>LMDPE</fullName>
            </value>
            <value>
                <fullName>MDPE</fullName>
            </value>
            <value>
                <fullName>sHDPE</fullName>
            </value>
            <value>
                <fullName>sLLDPE</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/PricebookEntry/fields/Family_Adj_Amt__c.field-meta.xml
<CustomField>
    <fullName>Family_Adj_Amt__c</fullName>
    <label>Family Adj Amt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/PricebookEntry/fields/Manual_Override_Amt__c.field-meta.xml
<CustomField>
    <fullName>Manual_Override_Amt__c</fullName>
    <label>Manual Override Amt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/PricebookEntry/fields/Past_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Past_Revenue__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Past Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/PricebookEntry/fields/Product_Adj_Amt__c.field-meta.xml
<CustomField>
    <fullName>Product_Adj_Amt__c</fullName>
    <label>Product Adj Amt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/PricebookEntry/fields/Product_Family_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Family_Name__c</fullName>
    <label>Product Family</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/PricebookEntry/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/PricebookEntry/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Invalidated</fullName>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Product2/fields/Density_Family__c.field-meta.xml
<CustomField>
    <fullName>Density_Family__c</fullName>
    <label>Density</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Division__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Density</valueSetName>
    </valueSet>
</CustomField>

objects/Product_Adjustment__c/Product_Adjustment__c.object-meta.xml
<CustomObject>
    <label>Product Adjustment</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Product Adjustment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Adjustment__c/fields/Density__c.field-meta.xml
<CustomField>
    <fullName>Density__c</fullName>
    <label>Density</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Density</valueSetName>
    </valueSet>
</CustomField>

objects/Product_Adjustment__c/fields/Product_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Product_Adjustment__c</fullName>
    <label>Product Adjustment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Product_Family__c/Product_Family__c.object-meta.xml
<CustomObject>
    <label>Product Family</label>
    <nameField>
        <label>Product Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Revenue__c/Product_Revenue__c.object-meta.xml
<CustomObject>
    <label>Product Revenue</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Revenue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sbaa__Approval__c/sbaa__Approval__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sbaa__Approval__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/PriceBookGeneration.cls
public with sharing class PriceBookGeneration {
    private Id pricebookId;
    //private static final String Query = 'SELECT Id,Name,Density_Family__c,Family FROM Product2 WHERE IsActive = true';
    private static final String Query = 'SELECT Id,Name,Family FROM Product2 WHERE IsActive = true';
    //public static sbaa__Approval__c[] approvals {get; set;} 

    public PriceBookGeneration(ApexPages.StandardController stdController) {
        pricebookId = stdController.getId();
    }
    
    @AuraEnabled
    public static List<PricebookEntry> getInitResult(String recordId)
    {
        List<PricebookEntry> pbEntryList = [SELECT Product2Id,Name,Product_Family_Name__c,Density__c,Base_Price__c,Family_Adj_Amt__c,Product_Adj_Amt__c,Manual_Override_Amt__c,UnitPrice,Past_Revenue__c,Quantity__c,Start_Date__c,End_date__c,Status__c FROM PriceBookEntry WHERE  Pricebook2Id = :recordId];
        return pbEntryList;
    }
    
    @AuraEnabled
    public static List<PricebookEntry> getProductRecords(String recordId){
        String family = '';
        Decimal mOverride = 0.0;
        Date startDate;
        Date endDate;
        List<PricebookEntry> generatedRecords =  new List<PricebookEntry>();
        List<PricebookEntry> priceListRecords = new List<PricebookEntry>();

        //Delete all Current records in PricebookEntry
        PricebookEntry[] deletePBEntryList = [SELECT Id FROM PriceBookEntry WHERE  Pricebook2Id = :recordId];
        try {
            delete deletePBEntryList;

        } catch (DmlException e) {
            System.debug('A DML Exception has occured on Delete:'+e.getMessage());
        }
   
        List <Pricebook2> pbList = [SELECT Product_Family__c,Manual_Override__c,Start_Date__c,End_date__c FROM Pricebook2 WHERE Id = :recordId];
            for(Pricebook2 priceBook : pbList){
                family = priceBook.Product_Family__c;
                mOverride = priceBook.Manual_Override__c;
                startDate = priceBook.Start_Date__c;
                endDate = priceBook.End_date__c;
        }
        
        System.debug('Values '+mOverride +' '+family + ' ' +startDate + ' '+endDate);

        //Fetch all Current records in Family_Price_Adjustment   
        List<Family_Price_Adjustment__c> fAdjList = [SELECT Product_Family__c,Family_Adjustment__c FROM Family_Price_Adjustment__c 
                                                              WHERE State__c='Approved' AND Start_Date__c <= :startDate AND End_Date__c >= :endDate];
        Map<String,Decimal> mapFamilyAdj = new Map<String,Decimal>();
        if (fAdjList.size()>0){
            for (Family_Price_Adjustment__c fAdj : fAdjList)
            {
                mapFamilyAdj.put(fAdj.Product_Family__c, fAdj.Family_Adjustment__c);
            }
        }
        //Fetch all Current records in Product_Adjustment   
        List<Product_Adjustment__c> pAdjList = [SELECT Density__c,Product_Adjustment__c FROM Product_Adjustment__c  
                                                             WHERE State__c='Approved' AND Start_Date__c <= :startDate AND End_Date__c >= :endDate];
        Map<String,Decimal> mapProductAdj = new Map<String,Decimal>();
        if (pAdjList.size()>0){
            for (Product_Adjustment__c pAdj :pAdjList)
            {
                mapProductAdj.put(pAdj.Density__c, pAdj.Product_Adjustment__c);
            }
        }
        
        List<Product2> productRecords = Database.query(getProductQuery(family));
            if (productRecords.size()>0){
                for(Product2 product : productRecords){
                    PricebookEntry pbEntry = new PricebookEntry();
                    pbEntry.Product2Id = product.Id;
                    pbEntry.Pricebook2Id = recordId;
                    //pbEntry.Density__c = product.Density_Family__c;
                      pbEntry.Density__c = 'N/A';
                    pbEntry.Product_Family_Name__c = product.Family;
                    String productName = product.Name;
                    String productFamily = product.Family;
                    System.debug('Product family:' + productFamily + 'productName:' +productName);

                    Decimal basePrice = 0.0;
                    List <Base_Price_Policy__c> basePriceList = [SELECT Base_Price__c FROM Base_Price_Policy__c WHERE 
                    Product_Family__c = :productFamily  AND Product_Name__c = :productName AND Status__c='Approved' AND Start_Date__c <= :startDate AND End_Date__c >= :endDate];
                    for(Base_Price_Policy__c bPriceRecord : basePriceList){
                        basePrice = bPriceRecord.Base_Price__c;
                    }
                    System.debug('Base Price' + basePrice);
                    pbEntry.Base_Price__c = basePrice;
                    
                    Decimal fAdjValue = mapFamilyAdj.get(productFamily);
                    System.debug('Family Adj ' +fAdjValue);
                    Decimal familyAdjAmt = 0.0;
                    if (fAdjValue != Null){
                        familyAdjAmt =basePrice * fAdjValue * 0.01;
                    }
                    pbEntry.Family_Adj_Amt__c = familyAdjAmt;
                    
                    //Decimal pAdjValue = mapProductAdj.get(product.Density_Family__c);
                     Decimal pAdjValue = 0;//mapProductAdj.get(product.Density_Family__c);
                    System.debug('Product Adj ' +pAdjValue);
                    Decimal productAdjAmt = 0.0;
                    if (pAdjValue != Null){
                        productAdjAmt =  basePrice  * pAdjValue * 0.01;
                    }
                    pbEntry.Product_Adj_Amt__c = productAdjAmt;
                    System.debug('Values '+fAdjValue +' '+pAdjValue+ ' '+startDate +' '+endDate);
                    
                    if (mOverride == NULL)
                    {
                        pbEntry.Manual_Override_Amt__c = 0;
                        Decimal listPrice = basePrice + familyAdjAmt + productAdjAmt;
                        pbEntry.UnitPrice = listPrice;
                    }
                    else
                    {   
                        Decimal mOverrideAmt = mOverride * basePrice * 0.01;
                        pbEntry.Manual_Override_Amt__c = mOverrideAmt;
                        Decimal listPrice = basePrice + mOverrideAmt; 
                        pbEntry.UnitPrice = listPrice;
                    }
                    pbEntry.Start_Date__c = startDate;
                    pbEntry.End_date__c = endDate;
                    pbEntry.Status__c = 'Generated';
                    pbEntry.IsActive=true;
                    pbEntry.UseStandardPrice=false;
                    pbEntry = setProductRevenue(pbEntry,productName);
                    if (pbEntry.Quantity__c != NULL){
                        pbEntry.Target_Revenue__c = pbEntry.UnitPrice * pbEntry.Quantity__c;
                    }
                    priceListRecords.add(pbEntry);
                }
                    try {
                        insert priceListRecords;
                    } catch (DmlException e) {
                        System.debug('A DML Exception has occured on Insert:'+e.getMessage());
                    }
                System.debug('Generated Records'+generatedRecords);
            }
        generatedRecords = [SELECT Product2Id,Name,Product_Family_Name__c,Density__c,Base_Price__c,Family_Adj_Amt__c,Product_Adj_Amt__c,Manual_Override_Amt__c,UnitPrice,Past_Revenue__c,Quantity__c,Start_Date__c,End_date__c,Status__c FROM PriceBookEntry WHERE  Pricebook2Id = :recordId];
        System.debug('Generated Records'+generatedRecords);
        return generatedRecords;
    }
    
    private static PricebookEntry setProductRevenue(PricebookEntry pbEntry,String productName){
        List <Product_Revenue__c> prList = [SELECT Past_Revenue__c,Quantity__c FROM Product_Revenue__c WHERE Name = :productName];
        if (prList.size()>0){
            for(Product_Revenue__c prRecord : prList){
                pbEntry.Past_Revenue__c = prRecord.Past_Revenue__c;
                pbEntry.Quantity__c = prRecord.Quantity__c;
            }
            
        }
        return pbEntry;
    }

    //Based on the product family value,Query String is returned
    private static String getProductQuery(String family){
        String queryString = QUERY;
        if (family == Null){
             System.debug('Query: ' +queryString);
        }
        else{
            queryString = QUERY + ' AND Family = :family';
            System.debug('Query: ' +queryString);
        }
        return queryString;
    }

 /*   @AuraEnabled
    public static void setPBEntryRecords(String pbrecords,String recordId){
        List<Product2> wrapperList = (List<Product2>)System.JSON.deserialize(pbrecords, List<Product2>.class);
        for(Product2 product : wrapperList){
            PricebookEntry pbEntry = new PricebookEntry();
            pbEntry.Product2Id = product.Id;
            pbEntry.Pricebook2Id = recordId;
            pbEntry.UnitPrice = 7000;
            pbEntry.IsActive=true;
            pbEntry.UseStandardPrice=false;
             try {
                 insert pbEntry;
             } catch (DmlException e) {
                 System.debug('A DML Exception has occured on Insert:'+e.getMessage());
             }
        }
    }*/

    @AuraEnabled
    public static void onSubmit(String recordId) {
        if (recordId != null) {
            //sbaa.ApprovalAPI.submit(recordId, sbaa__Approval__c.Price_Book__c);
        }
    }
    
    public void onPreview() {
        if (pricebookId != null) {
            //approvals = sbaa.ApprovalAPI.preview(pricebookId, sbaa__Approval__c.Price_Book__c);
        }
    }
}