objects/Mass_Price_Update__c/Mass_Price_Update__c.object-meta.xml
<CustomObject>
    <label>Mass Price Update</label>
    <nameField>
        <displayFormat>MPU-{0000}</displayFormat>
        <label>Mass Price Update Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Price Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MPU_Filter_Criteria__c/MPU_Filter_Criteria__c.object-meta.xml
<CustomObject>
    <label>MPU Filter Criteria</label>
    <nameField>
        <label>MPU Filter Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MPU Filter Criterias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote_Line_Change_Detail__c/Quote_Line_Change_Detail__c.object-meta.xml
<CustomObject>
    <label>Quote Line Change Detail</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Line Change Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote_Line_Change_Detail__c/fields/Mass_Price_Update__c.field-meta.xml
<CustomField>
    <fullName>Mass_Price_Update__c</fullName>
    <label>Mass Price Update</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DeleteTest.cls
public class DeleteTest {
    public DeleteTest(){
        
    }
    public void  Test(){
          List<Mass_Price_Update__c> ids = [select Id from Mass_Price_Update__c];
         delete ids;
        
        List<MPU_Filter_Criteria__c> idss = [select Id from MPU_Filter_Criteria__c];
        delete idss;
          List<Quote_Line_Change_Detail__c> chids = [select Id from Quote_Line_Change_Detail__c];
		 delete chids;
          //  system.debug('Change Detail '+chids);
		 // List<SBQQ__Quote__c> ids = [select Id from SBQQ__Quote__c];
         	//  List<Account> ids = [select Id from Account where Name = 'Quote MPU New'];
			//delete ids;		
            
        //  List<SBQQ__ContractedPrice__c> cids = [select Id from SBQQ__ContractedPrice__c where SBQQ__Product__r.Name = 'MPU Product'];
         //delete cids;
              //        List<Quote_Line_Change_Detail__c> chids = [select Id from Quote_Line_Change_Detail__c];
  			//delete chids;
    }

}