objects/Account/fields/Account_Channel__c.field-meta.xml
<CustomField>
    <fullName>Account_Channel__c</fullName>
    <label>Account Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Channel</valueSetName>
    </valueSet>
</CustomField>

objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Customer_Classification__c.field-meta.xml
<CustomField>
    <fullName>Customer_Classification__c</fullName>
    <label>Customer Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Customer_Classification</valueSetName>
    </valueSet>
</CustomField>

objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <label>Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <restricted>true</restricted>
        <valueSetName>Division</valueSetName>
    </valueSet>
</CustomField>

classes/ApplySpecificFilterController.cls
public with sharing class ApplySpecificFilterController {
    private static final String accQuery = 'Select Id,Name from Account order by Name asc';
    private static final String countryQuery = 'Select Id,Name from Country__c order by Name asc';
    private static final String prodFamilyQuery = 'Select Id,Family from Product2 where Family != null';
    private static final String divisionQuery = 'Select Id,Division__c from Product2 where Division__c != null';
    private static final String prodQuery = 'Select Id,Name from Product2 order by Name asc';
    private static final String accChannelQuery = 'Select Id,Account_Channel__c from Account where Account_Channel__c!=null';
    private static final String accClassQuery = 'Select Id,Customer_Classification__c from Account where Customer_Classification__c!=null';


    public ApplySpecificFilterController() {

    }

    @AuraEnabled
    public static List<Account> getAccountList(){
        List<Account> accList = Database.query(accQuery);
        return accList;
    }
    @AuraEnabled
    public static List<Country__c> getRegionList(){
        List<Country__c> countryList = Database.query(countryQuery);
        return countryList;
    }
    @AuraEnabled
    public static List<Product2> getProdFamilyList(){
       List<Product2> prodFamilyList = Database.query(prodFamilyQuery);
        System.debug('prodFamilyList------------'+prodFamilyList);
        return prodFamilyList;
    }
    @AuraEnabled
    public static List<Product2> getDivisionList(){
        List<Product2> divisionList = Database.query(divisionQuery);
        System.debug('divisionList------------'+divisionList);
        return divisionList;
    }
   
    @AuraEnabled
    public static List<Product2> getProductList(){
        List<Product2> prodList = Database.query(prodQuery);
        return prodList;
    }
    @AuraEnabled
    public static List<Account> getAccChannelList(){
        List<Account> accChannelList = Database.query(accChannelQuery);
        return accChannelList;
    }
    @AuraEnabled
    public static List<Account> getAccClassList(){
        List<Account> accClassList = Database.query(accClassQuery);
        return accClassList;
    }
}