objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <label>Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Mass_Price_Update__c/Mass_Price_Update__c.object-meta.xml
<CustomObject>
    <label>Mass Price Update</label>
    <nameField>
        <displayFormat>MPU-{0000}</displayFormat>
        <label>Mass Price Update Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Price Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Mass_Price_Update__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold To Geo</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Mass Price Updates</relationshipLabel>
    <relationshipName>Mass_Price_Updates</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Product2/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <restricted>true</restricted>
        <valueSetName>Division</valueSetName>
    </valueSet>
</CustomField>

objects/Product_Family__c/Product_Family__c.object-meta.xml
<CustomObject>
    <label>Product Family</label>
    <nameField>
        <label>Product Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Division</label>
    <referenceTo>Division__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SBQQ__QuoteLine__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Family</label>
    <referenceTo>Product_Family__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/ApplySpecificFilterControllerTest.cls
@isTest(SeeAllData=true)
public class ApplySpecificFilterControllerTest {
    //MPUController testCont = new MPUController();
    //testCont.createQuote();
    /*SBQQ__QuoteLine__c qteLine = [Select Id from SBQQ__QuoteLine__c LIMIT 1];
    SBQQ__QuoteLine__c qteLineValue = MPUController.findQuoteLineById(qteLine.Id);
    String recordId = [Select Id from Mass_Price_Update__c LIMIT 1].Id;
    List <MPUProductUpdateWrapper> mpuProdWrapper = MPUController.getQuoteLinesByRecordId(recordId,'');*/
    static testmethod void myTest(){
        Account a = new Account(name='accountmember1');
        insert a;
        ApplySpecificFilterController.getAccountList();
        Country__c c = new ExperisPricing__Country__c(name='TestCountry');
        insert c;
        ApplySpecificFilterController.getRegionList();
        Product_Family__c pf = new ExperisPricing__Product_Family__c(name='TestProductFamily');
        insert pf;
        ApplySpecificFilterController.getProdFamilyList();
        Division__c div = new Division__c(name='TestDivision');
        insert div;
        ApplySpecificFilterController.getDivisionList();
        Product2 prod = new Product2(name='TestProductName');
        insert prod;
        ApplySpecificFilterController.getProductList();
        
       // String recordId = [Select Id from Mass_Price_Update__c LIMIT 1].Id;
       // MPUProductUpdateWrapper mpuProdWrapper =  new MPUProductUpdateWrapper();
       // MPUController.getQuoteLinesByRecordId(recordId,'');       
    }
}